Install vim plug for new spin instance

diff --git a/src/zshrc b/src/zshrc
--- a/src/zshrc
+++ b/src/zshrc
@@ -4,11 +4,20 @@
 
 alias vim='nvim'
 
-# Installing FZF
-git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
-~/.fzf/install
-[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
-sudo rm -rf /usr/local/bin/fzf
-sudo rm -rf /usr/bin/fzf
+# Installing Vim plug
+if [ ! -f ~/.config/nvim/autoload/plug.vim ]; then
+    echo "Vim-Plug not found, installing..."
+    curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
+	    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
+fi
 
+# Installing FZF
+if ! command -v fzf &> /dev/null
+then
+	git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
+	~/.fzf/install --key-bindings --update-rc
+	[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
+	sudo rm -rf /usr/local/bin/fzf
+	sudo rm -rf /usr/bin/fzf
+fi
 export PS1="%d \$ "
